### ISSUE TITLE
add api token in travis

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/now-fleet#2]
see https://github.com/vigour-io/boilerplate-module, adding the token will allow you to run 'real' tests on travis (safely)

**Comment by mstdokumaci** [comment]
unit tests are already running on travis as i can see. added npm token for publishing too. any other token i'm missing?

**Comment by youzi** [comment]
@mstdokumaci @jimdebeer That should be all.

**Comment by mstdokumaci** [comment]
@youzi thanks.
